In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('/content/Training.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Training.csv'

In [ ]:
df.shape

NameError: name 'df' is not defined

In [ ]:
len(df['prognosis'].unique())

41

In [ ]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

train test split

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
X = df.drop('prognosis', axis=1)
y = df['prognosis']

In [ ]:
le = LabelEncoder()
Y = le.fit_transform(y)


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

training top models


In [ ]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [ ]:
#create a dictionary to store models

models = {
    'SVC': SVC(kernel="linear"),
    'RandomForestClassifier': RandomForestClassifier(),
    'GradientBoostingClassifier': GradientBoostingClassifier(),
    'AdaBoostClassifier': AdaBoostClassifier(),
    'LogisticRegression': LogisticRegression(),
    'KNeighborsClassifier': KNeighborsClassifier(),
}

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

for model_name, model in models.items():
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)  # fixed typo
    cm = confusion_matrix(y_test, predictions)

    print(f"Model: {model_name}")
    print(f"Accuracy Score: {accuracy}")
    print(f"Confusion Matrix:\n{cm}\n")


Model: SVC
Accuracy Score: 1.0
Confusion Matrix:
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

Model: RandomForestClassifier
Accuracy Score: 1.0
Confusion Matrix:
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

Model: GradientBoostingClassifier
Accuracy Score: 1.0
Confusion Matrix:
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

Model: AdaBoostClassifier
Accuracy Score: 0.10298102981029811
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Model: LogisticRegression
Accuracy Score: 1.0
Confusion Matrix:
[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]


In [ ]:
svc = SVC(kernel="linear")
svc.fit(X_train, y_train)
predictions = svc.predict(X_test)
accuracy_score(y_test, predictions)

1.0

In [ ]:
import pickle

pickle.dump(svc,open("svc.pkl","wb"))

NameError: name 'svc' is not defined

In [ ]:
with open('/content/svc.pkl', 'rb') as f:  # 'rb' = read binary
    svc = pickle.load(f)

load database and use logic for recommendations

In [ ]:
# sym_des = pd.read_csv("/content/symtoms_df.csv")
precautions = pd.read_csv("/content/precautions_df.csv")
workout = pd.read_csv("/content/workout_df.csv")
diets = pd.read_csv("/content/diets.csv")
description = pd.read_csv("/content/description.csv")
medications = pd.read_csv("/content/medications.csv")

In [ ]:
workout



Unnamed: 0.1  Unnamed: 0           disease  \
0               0           0  Fungal infection   
1               1           1  Fungal infection   
2               2           2  Fungal infection   
3               3           3  Fungal infection   
4               4           4  Fungal infection   
..            ...         ...               ...   
405           405         405          Impetigo   
406           406         406          Impetigo   
407           407         407          Impetigo   
408           408         408          Impetigo   
409           409         409          Impetigo   

                               workout  
0                   Avoid sugary foods  
1                   Consume probiotics  
2            Increase intake of garlic  
3               Include yogurt in diet  
4                Limit processed foods  
..                                 ...  
405  Consult a healthcare professional  
406     Follow medical recommendations  
407                   Avoid scratching  
408        Take prescribed antibiotics  
409                Practice wound care  

[410 rows x 4 columns]

In [ ]:


def helper(dis):
  desc = description[description['Disease'] == dis]['Description']
  desc = " ".join([w for w in desc])

  pre = precautions[precautions['Disease'] == dis][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']]
  pre = [i for i in pre.values]

  med = medications[medications['Disease'] == dis]['Medication']
  med = [i for i in med.values]

  die = diets[diets['Disease'] == dis]['Diet']
  die = [i for i in die.values]

  work = workout[workout['disease'] == dis]['workout']
  work = [i for i in work.values]

  return desc,pre , med,die,work



#model predictions function
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


def get_prediction_value(patient_symptoms):
  input_vector = np.zeros(len(symptoms_dict))
  for item in patient_symptoms:
    input_vector[symptoms_dict[item]] = 1
  return diseases_list[svc.predict([input_vector])[0]]



In [ ]:
#test 1
symptoms = input("Enter your symptoms.....")
user_symptoms = [s.strip() for s in symptoms.split(',')]

#remove any extra characters , if any

user_symptoms = [sym.strip("[]' ") for sym in user_symptoms]

# user_symptoms

predicted_disease = get_prediction_value(user_symptoms)
predicted_disease

desc , pre, med , diet , wrkout  = helper(predicted_disease)
desc,pre , med,diet,wrkout
# desc,pre,med,diet,wrkout

Enter your symptoms.....itching


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


('Fungal infection is a common skin condition caused by fungi.',
 [array(['bath twice', 'use detol or neem in bathing water',
         'keep infected area dry', 'use clean cloths'], dtype=object)],
 ["['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"],
 ["['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"],
 ['Avoid sugary foods',
  'Consume probiotics',
  'Increase intake of garlic',
  'Include yogurt in diet',
  'Limit processed foods',
  'Stay hydrated',
  'Consume green tea',
  'Eat foods rich in zinc',
  'Include turmeric in diet',
  'Eat fruits and vegetables'])